import { Badge, Category, Checkin, Organization, Place, QRCode, Quest, QuestStep, UserBadge, UserProfile, UserProgress } from './types'

const now = new Date().toISOString()

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-ngo', name: 'Organizacje społeczne', slug: 'organizacje-spoleczne', icon: '🤝', color: '#22c55e', type: 'ngo', created_at: now },
  { id: 'cat-help', name: 'Pomoc społeczna', slug: 'pomoc-spoleczna', icon: '🏠', color: '#0ea5e9', type: 'ngo', created_at: now },
  { id: 'cat-culture', name: 'Kultura i edukacja', slug: 'kultura-edukacja', icon: '🎭', color: '#a855f7', type: 'all', created_at: now },
  { id: 'cat-city', name: 'Miejsca miejskie', slug: 'miejsca-miejskie', icon: '🏛️', color: '#f59e0b', type: 'place', created_at: now },
  { id: 'cat-quest', name: 'Questy', slug: 'questy', icon: '🗺️', color: '#ef4444', type: 'quest', created_at: now },
]

export const DEMO_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-zf',
    name: 'Fundacja Zakątek Fantastyki',
    slug: 'fundacja-zakatek-fantastyki',
    short_description: 'Edukacja, fantastyka i aktywność społeczna dla dzieci, młodzieży i dorosłych.',
    description: 'Fundacja prowadzi działania edukacyjne, integracyjne i kulturalne, organizuje wydarzenia, gry terenowe i aktywności społeczne.',
    activity_areas: ['edukacja', 'kultura', 'integracja'],
    support_types: ['warsztaty', 'wydarzenia', 'wolontariat'],
    recipient_groups: ['dzieci', 'młodzież', 'rodziny'],
    address: 'Bielsko-Biała',
    city: 'Bielsko-Biała',
    latitude: 49.8224,
    longitude: 19.0444,
    phone: '+48 000 000 000',
    email: 'kontakt@zakatekfantastyki.pl',
    website: 'https://zakatekfantastyki.pl',
    opening_hours: { mon: 'po uzgodnieniu', tue: 'po uzgodnieniu', wed: 'po uzgodnieniu', thu: 'po uzgodnieniu', fri: 'po uzgodnieniu', notes: 'Najlepiej kontaktować się mailowo.' },
    accessibility_info: 'Kontakt online oraz działania terenowe w różnych lokalizacjach.',
    is_accessible: true,
    cover_image: null,
    gallery: [],
    category_id: 'cat-ngo',
    is_active: true,
    is_promoted: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'org-wsp',
    name: 'Centrum Wsparcia Sąsiedzkiego',
    slug: 'centrum-wsparcia-sasiedzkiego',
    short_description: 'Punkt informacji o pomocy, wolontariacie i lokalnych inicjatywach.',
    description: 'Miejsce, w którym mieszkańcy mogą znaleźć informacje o usługach społecznych, wolontariacie i oddolnych inicjatywach.',
    activity_areas: ['pomoc', 'wolontariat'],
    support_types: ['informacja', 'doradztwo', 'wolontariat'],
    recipient_groups: ['mieszkańcy', 'seniorzy', 'rodziny'],
    address: 'ul. 11 Listopada 10, Bielsko-Biała',
    city: 'Bielsko-Biała',
    latitude: 49.8209,
    longitude: 19.0448,
    phone: '+48 111 222 333',
    email: 'biuro@centrumwsparcia.pl',
    website: 'https://example.org',
    opening_hours: { mon: '10:00–16:00', tue: '10:00–16:00', wed: '10:00–18:00', thu: '10:00–16:00', fri: '10:00–14:00' },
    accessibility_info: 'Wejście z poziomu ulicy.',
    is_accessible: true,
    cover_image: null,
    gallery: [],
    category_id: 'cat-help',
    is_active: true,
    is_promoted: true,
    created_at: now,
    updated_at: now,
  },
]

export const DEMO_BADGES: Badge[] = [
  { id: 'badge-ngo', name: 'Odkrywca NGO', description: 'Za ukończenie pierwszego questu społecznego.', image: null, quest_id: 'quest-ngo', criteria: null, created_at: now },
]

export const DEMO_PLACES: Place[] = [
  {
    id: 'place-zf',
    name: 'Zakątek Fantastyki',
    slug: 'zakatek-fantastyki',
    type: 'ngo',
    short_description: 'Poznaj organizację tworzącą wydarzenia, gry i działania edukacyjne.',
    description: 'To punkt startowy do poznawania lokalnych organizacji i aktywności miejskich.',
    full_description: 'Zakątek Fantastyki pokazuje, jak NGO może łączyć edukację, kulturę i integrację. To dobre miejsce, by zacząć przygodę z NGOcachingiem.',
    latitude: 49.8224,
    longitude: 19.0444,
    address: 'Bielsko-Biała',
    category_id: 'cat-ngo',
    organization_id: 'org-zf',
    cover_image: null,
    gallery: [],
    hint: 'Poszukaj miejsca związanego z lokalną aktywnością społeczną.',
    task_content: 'Podejdź do punktu i zalicz go przez GPS.',
    unlockable_content: 'Brawo! Właśnie odkryłeś pierwszy punkt społeczny w Bielsku-Białej.',
    verification_type: 'gps',
    verification_data: { radius: 120 },
    gps_radius: 120,
    is_active: true,
    is_promoted: true,
    event_start: null,
    event_end: null,
    accessibility: 'publiczne miejsce spotkań',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'place-wsparcie',
    name: 'Centrum Wsparcia Sąsiedzkiego',
    slug: 'centrum-wsparcia-sasiedzkiego',
    type: 'ngo',
    short_description: 'Dowiedz się, gdzie szukać informacji o pomocy i wolontariacie.',
    description: 'Punkt pokazuje, jak lokalne organizacje i miejsca wsparcia pomagają mieszkańcom w codziennych sprawach.',
    full_description: 'To przykład miejsca, gdzie można uzyskać informacje o wsparciu społecznym, działaniach wolontariackich i lokalnych inicjatywach.',
    latitude: 49.8209,
    longitude: 19.0448,
    address: 'ul. 11 Listopada 10, Bielsko-Biała',
    category_id: 'cat-help',
    organization_id: 'org-wsp',
    cover_image: null,
    gallery: [],
    hint: 'Rozejrzyj się za informacją o mieszkańcach i pomocy.',
    task_content: 'Wpisz hasło: pomoc',
    unlockable_content: 'Pomoc jest bliżej, niż myślisz — często wystarczy wiedzieć, gdzie zapytać.',
    verification_type: 'password',
    verification_data: { password: 'pomoc' } as any,
    gps_radius: 80,
    is_active: true,
    is_promoted: true,
    event_start: null,
    event_end: null,
    accessibility: 'wejście bez schodów',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'place-rynek',
    name: 'Rynek Bielska-Białej',
    slug: 'rynek-bielska-bialej',
    type: 'city',
    short_description: 'Klasyczny punkt miejski, od którego łatwo zacząć spacer po centrum.',
    description: 'Rynek to dobre miejsce, by zacząć miejski quest i złapać orientację w centrum.',
    full_description: 'W tym punkcie możesz rozpocząć eksplorację miasta i odkrywać kolejne miejsca w Bielsku-Białej.',
    latitude: 49.8228,
    longitude: 19.0461,
    address: 'Rynek, Bielsko-Biała',
    category_id: 'cat-city',
    organization_id: null,
    cover_image: null,
    gallery: [],
    hint: 'Szukaj serca starego miasta.',
    task_content: 'Odpowiedz: jakie miasto odkrywasz? Wpisz „Bielsko”.',
    unlockable_content: 'Centrum miasta to świetny punkt startowy dla kolejnych questów.',
    verification_type: 'answer',
    verification_data: { question: 'Jakie miasto odkrywasz?', answer: 'bielsko' } as any,
    gps_radius: 100,
    is_active: true,
    is_promoted: false,
    event_start: null,
    event_end: null,
    accessibility: 'przestrzeń publiczna',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'place-zamek',
    name: 'Zamek Sułkowskich',
    slug: 'zamek-sulkowskich',
    type: 'quest',
    short_description: 'Etap questu prowadzący przez ważne miejsca Bielska-Białej.',
    description: 'Jedno z najbardziej rozpoznawalnych miejsc w mieście.',
    full_description: 'Ten etap łączy warstwę miejską z warstwą edukacyjną — możesz odkrywać historię i kontekst społeczny miejsca.',
    latitude: 49.8220,
    longitude: 19.0472,
    address: 'ul. Wzgórze 16, Bielsko-Biała',
    category_id: 'cat-city',
    organization_id: null,
    cover_image: null,
    gallery: [],
    hint: 'Poszukaj zabytku górującego nad okolicą.',
    task_content: 'Zeskanuj kod QR albo wpisz ręcznie: BIELSKO-ZAMEK',
    unlockable_content: 'Odkryłeś ważne miejsce na mapie miasta.',
    verification_type: 'qr',
    verification_data: { qr_code_id: 'qr-zamek' },
    gps_radius: 90,
    is_active: true,
    is_promoted: false,
    event_start: null,
    event_end: null,
    accessibility: 'przestrzeń publiczna w pobliżu',
    created_at: now,
    updated_at: now,
  },
]

export const DEMO_QUESTS: Quest[] = [
  {
    id: 'quest-ngo',
    title: 'Odkryj NGO w Bielsku-Białej',
    slug: 'odkryj-ngo-w-bielsku-bialej',
    description: 'Krótki quest prowadzący przez punkty społeczne i pokazujący, czym zajmują się lokalne organizacje.',
    theme: 'społeczne bielsko',
    cover_image: null,
    difficulty: 'easy',
    estimated_time: 60,
    completion_conditions: { min_steps: 2 },
    reward_description: 'Po ukończeniu dostajesz odznakę Odkrywca NGO.',
    badge_id: 'badge-ngo',
    is_active: true,
    is_featured: true,
    category_id: 'cat-quest',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'quest-city',
    title: 'Spacer przez centrum',
    slug: 'spacer-przez-centrum',
    description: 'Lekki miejski quest po charakterystycznych punktach centrum Bielska-Białej.',
    theme: 'miasto',
    cover_image: null,
    difficulty: 'easy',
    estimated_time: 45,
    completion_conditions: { min_steps: 2 },
    reward_description: 'Poznasz dwa ważne punkty centrum miasta.',
    badge_id: null,
    is_active: true,
    is_featured: false,
    category_id: 'cat-quest',
    created_at: now,
    updated_at: now,
  },
]

export const DEMO_QUEST_STEPS: QuestStep[] = [
  { id: 'step-1', quest_id: 'quest-ngo', place_id: 'place-zf', step_number: 1, title: 'Poznaj pierwszą organizację', description: 'Zalicz punkt Zakątek Fantastyki.', hint: null, task_content: null, is_optional: false, created_at: now },
  { id: 'step-2', quest_id: 'quest-ngo', place_id: 'place-wsparcie', step_number: 2, title: 'Odkryj punkt wsparcia', description: 'Sprawdź miejsce, które pomaga mieszkańcom.', hint: null, task_content: null, is_optional: false, created_at: now },
  { id: 'step-3', quest_id: 'quest-city', place_id: 'place-rynek', step_number: 1, title: 'Start na rynku', description: 'Rozpocznij od serca miasta.', hint: null, task_content: null, is_optional: false, created_at: now },
  { id: 'step-4', quest_id: 'quest-city', place_id: 'place-zamek', step_number: 2, title: 'Dojdź do zabytku', description: 'Odkryj charakterystyczne miejsce na wzgórzu.', hint: null, task_content: null, is_optional: false, created_at: now },
]

export const DEMO_QR_CODES: QRCode[] = [
  { id: 'qr-zamek', code: 'BIELSKO-ZAMEK', place_id: 'place-zamek', is_active: true, is_single_use: false, scan_count: 0, created_at: now },
]

export const DEMO_USER_PROFILES: UserProfile[] = [
  {
    id: 'user-demo',
    username: 'demo',
    display_name: 'Demo Odkrywca',
    avatar_url: null,
    bio: 'Konto demonstracyjne do testów aplikacji.',
    explorer_level: 1,
    total_points: 0,
    home_city: 'Bielsko-Biała',
    is_admin: false as any,
    created_at: now,
    updated_at: now,
  } as UserProfile,
  {
    id: 'user-admin',
    username: 'admin',
    display_name: 'Admin Demo',
    avatar_url: null,
    bio: 'Administrator demonstracyjny.',
    explorer_level: 3,
    total_points: 120,
    home_city: 'Bielsko-Biała',
    is_admin: true as any,
    created_at: now,
    updated_at: now,
  } as UserProfile,
]

export const DEMO_AUTH_USERS = [
  { id: 'user-demo', email: 'demo@miejski.pl', password: 'demo123', is_admin: false },
  { id: 'user-admin', email: 'admin@miejski.pl', password: 'admin123', is_admin: true },
]

export const DEMO_CHECKINS: Checkin[] = []
export const DEMO_USER_PROGRESS: UserProgress[] = []
export const DEMO_USER_BADGES: UserBadge[] = []

