import { Badge, Category, Checkin, Organization, Place, QRCode, Quest, QuestStep, UserBadge, UserProfile, UserProgress } from './types'

const now = new Date().toISOString()

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-ngo', name: 'Organizacje społeczne', slug: 'organizacje-spoleczne', icon: '🤝', color: '#22c55e', type: 'ngo', created_at: now },
  { id: 'cat-help', name: 'Pomoc społeczna', slug: 'pomoc-spoleczna', icon: '🏠', color: '#0ea5e9', type: 'ngo', created_at: now },
  { id: 'cat-culture', name: 'Kultura i edukacja', slug: 'kultura-edukacja', icon: '🎭', color: '#a855f7', type: 'all', created_at: now },
  { id: 'cat-city', name: 'Miejsca miejskie', slug: 'miejsca-miejskie', icon: '🏛️', color: '#f59e0b', type: 'place', created_at: now },
  { id: 'cat-quest', name: 'Questy', slug: 'questy', icon: '🗺️', color: '#ef4444', type: 'quest', created_at: now },
]

export const DEMO_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-zf',
    name: 'Fundacja Zakątek Fantastyki',
    slug: 'fundacja-zakatek-fantastyki',
    short_description: 'Edukacja, fantastyka i aktywność społeczna dla dzieci, młodzieży i dorosłych.',
    description: 'Fundacja prowadzi działania edukacyjne, integracyjne i kulturalne, organizuje wydarzenia, gry terenowe i aktywności społeczne.',
    activity_areas: ['edukacja', 'kultura', 'integracja'],
    support_types: ['warsztaty', 'wydarzenia', 'wolontariat'],
    recipient_groups: ['dzieci', 'młodzież', 'rodziny'],
    address: 'Bielsko-Biała',
    city: 'Bielsko-Biała',
    latitude: 49.8224,
    longitude: 19.0444,
    phone: '+48 000 000 000',
    email: 'kontakt@zakatekfantastyki.pl',
    website: 'https://zakatekfantastyki.pl',
    opening_hours: { mon: 'po uzgodnieniu', tue: 'po uzgodnieniu', wed: 'po uzgodnieniu', thu: 'po uzgodnieniu', fri: 'po uzgodnieniu', notes: 'Najlepiej kontaktować się mailowo.' },
    accessibility_info: 'Kontakt online oraz działania terenowe w różnych lokalizacjach.',
    is_accessible: true,
    cover_image: null,
    gallery: [],
    category_id: 'cat-ngo',
    is_active: true,
    is_promoted: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'org-wsp',
    name: 'Centrum Wsparcia Sąsiedzkiego',
    slug: 'centrum-wsparcia-sasiedzkiego',
    short_description: 'Punkt informacji o pomocy, wolontariacie i lokalnych inicjatywach.',
    description: 'Miejsce, w którym mieszkańcy mogą znaleźć informacje o usługach społecznych, wolontariacie i oddolnych inicjatywach.',
    activity_areas: ['pomoc', 'wolontariat'],
    support_types: ['informacja', 'doradztwo', 'wolontariat'],
    recipient_groups: ['mieszkańcy', 'seniorzy', 'rodziny'],
    address: 'ul. 11 Listopada 10, Bielsko-Biała',
    city: 'Bielsko-Biała',
    latitude: 49.8209,
    longitude: 19.0448,
    phone: '+48 111 222 333',
    email: 'biuro@centrumwsparcia.pl',
    website: 'https://example.org',
    opening_hours: { mon: '10:00–16:00', tue: '10:00–16:00', wed: '10:00–18:00', thu: '10:00–16:00', fri: '10:00–14:00' },
    accessibility_info: 'Wejście z poziomu ulicy.',
    is_accessible: true,
    cover_image: null,
    gallery: [],
    category_id: 'cat-help',
    is_active: true,
    is_promoted: true,
    created_at: now,
    updated_at: now,
  },
]

export const DEMO_BADGES: Badge[] = [
  { id: 'badge-ngo', name: 'Odkrywca NGO', description: 'Za ukończenie pierwszego questu społecznego.', image: null, quest_id: 'quest-ngo', criteria: null, created_at: now },
  { id: 'badge-odkrywca', name: 'Odkrywca Bielska', description: 'Za ukończenie spaceru przez centrum Bielska-Białej.', image: null, quest_id: 'quest-city', criteria: null, created_at: now },
]

// ─── MIEJSCA NGO (quest „Odkryj NGO") ──────────────────────────────────────────

export const DEMO_PLACES: Place[] = [
  {
    id: 'place-zf',
    name: 'Zakątek Fantastyki',
    slug: 'zakatek-fantastyki',
    type: 'ngo',
    short_description: 'Poznaj organizację tworzącą wydarzenia, gry i działania edukacyjne.',
    description: 'To punkt startowy do poznawania lokalnych organizacji i aktywności miejskich.',
    full_description: 'Zakątek Fantastyki pokazuje, jak NGO może łączyć edukację, kulturę i integrację. To dobre miejsce, by zacząć przygodę z NGOcachingiem.',
    latitude: 49.8224,
    longitude: 19.0444,
    address: 'Bielsko-Biała',
    category_id: 'cat-ngo',
    organization_id: 'org-zf',
    cover_image: null,
    gallery: [],
    hint: 'Poszukaj miejsca związanego z lokalną aktywnością społeczną.',
    task_content: 'Podejdź do punktu i zalicz go przez GPS.',
    unlockable_content: 'Brawo! Właśnie odkryłeś pierwszy punkt społeczny w Bielsku-Białej.',
    verification_type: 'gps',
    verification_data: { radius: 120 },
    gps_radius: 120,
    is_active: true,
    is_promoted: true,
    event_start: null,
    event_end: null,
    accessibility: 'publiczne miejsce spotkań',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'place-wsparcie',
    name: 'Centrum Wsparcia Sąsiedzkiego',
    slug: 'centrum-wsparcia-sasiedzkiego',
    type: 'ngo',
    short_description: 'Dowiedz się, gdzie szukać informacji o pomocy i wolontariacie.',
    description: 'Punkt pokazuje, jak lokalne organizacje i miejsca wsparcia pomagają mieszkańcom w codziennych sprawach.',
    full_description: 'To przykład miejsca, gdzie można uzyskać informacje o wsparciu społecznym, działaniach wolontariackich i lokalnych inicjatywach.',
    latitude: 49.8209,
    longitude: 19.0448,
    address: 'ul. 11 Listopada 10, Bielsko-Biała',
    category_id: 'cat-help',
    organization_id: 'org-wsp',
    cover_image: null,
    gallery: [],
    hint: 'Rozejrzyj się za informacją o mieszkańcach i pomocy.',
    task_content: 'Wpisz hasło: pomoc',
    unlockable_content: 'Pomoc jest bliżej, niż myślisz — często wystarczy wiedzieć, gdzie zapytać.',
    verification_type: 'password',
    verification_data: { password: 'pomoc' } as any,
    gps_radius: 80,
    is_active: true,
    is_promoted: true,
    event_start: null,
    event_end: null,
    accessibility: 'wejście bez schodów',
    created_at: now,
    updated_at: now,
  },

  // ─── MIEJSCA QUESTU „Spacer przez centrum" ──────────────────────────────────

  {
    // Etap 1 — Rynek
    id: 'place-rynek',
    name: 'Rynek w Bielsku-Białej',
    slug: 'rynek-bielsko',
    type: 'city',
    short_description: 'Serce starego miasta — punkt startowy spaceru przez centrum.',
    description: 'Historyczny rynek Bielska-Białej otoczony kamienicami z XVII–XIX w. W centrum placu stoi fontanna Neptuna.',
    full_description: 'Rynek jest centralnym punktem starówki Bielska-Białej. Plac otaczają zabytkowe kamienice mieszczańskie, a w jego centrum stoi fontanna z posągiem Neptuna — jednym z symboli miasta.',
    latitude: 49.821111,
    longitude: 19.042500,
    address: 'Rynek, 43-300 Bielsko-Biała',
    category_id: 'cat-city',
    organization_id: null,
    cover_image: null,
    gallery: [],
    hint: 'Szukaj fontanny na środku rynku — co trzyma posąg?',
    task_content: 'Znajdź fontannę Neptuna. Co trzyma Neptun w dłoni?',
    unlockable_content: null,
    verification_type: 'answer',
    verification_data: {
      question: 'Co trzyma Neptun w dłoni?',
      answer: 'trójząb',
      accepted_answers: ['trójząb', 'trojzab', 'trojząb'],
    } as any,
    gps_radius: 60,
    is_active: true,
    is_promoted: true,
    event_start: null,
    event_end: null,
    accessibility: 'przestrzeń publiczna, płyta rynku',
    created_at: now,
    updated_at: now,
  },
  {
    // Etap 2 — Zamek Sułkowskich
    id: 'place-zamek',
    name: 'Zamek Książąt Sułkowskich',
    slug: 'zamek-sulkowskich',
    type: 'city',
    short_description: 'Średniowieczny zamek górujący nad centrum — jedna z ikon Bielska.',
    description: 'Zamek na wzgórzu to jeden z najważniejszych zabytków Bielska-Białej. Pierwotnie wzniesiony w XIV w., wielokrotnie przebudowywany.',
    full_description: 'Zamek Książąt Sułkowskich (wcześniej zamek książąt cieszyńskich) pochodzi z XIV wieku. Góruje nad starówką i przez wieki był siedzibą kolejnych władców miasta. Dziś mieści Muzeum w Bielsku-Białej.',
    latitude: 49.821760,
    longitude: 19.044569,
    address: 'Wzgórze 16, 43-300 Bielsko-Biała',
    category_id: 'cat-city',
    organization_id: null,
    cover_image: null,
    gallery: [],
    hint: 'Poszukaj tablicy informacyjnej lub opisu na murach zamku.',
    task_content: 'Spójrz na informacje o zamku. Z którego wieku pochodzi zamek?',
    unlockable_content: null,
    verification_type: 'answer',
    verification_data: {
      question: 'Z którego wieku pochodzi zamek?',
      answer: 'xiv',
      accepted_answers: ['xiv', '14', 'xiv wiek', '14 wiek', 'czternasty', 'XIV'],
    } as any,
    gps_radius: 60,
    is_active: true,
    is_promoted: false,
    event_start: null,
    event_end: null,
    accessibility: 'wzgórze, chodnik od ulicy',
    created_at: now,
    updated_at: now,
  },
  {
    // Etap 3 — Pomnik Bolka i Lolka
    id: 'place-bolek',
    name: 'Pomnik Bolka i Lolka',
    slug: 'pomnik-bolka-i-lolka',
    type: 'city',
    short_description: 'Bajkowi bohaterowie, którzy urodziło się właśnie tutaj — przy Sferze.',
    description: 'Bielsko-Biała to rodzinne miasto Bolka i Lolka — kultowych postaci Studia Filmów Rysunkowych. Pomnik stoi przy Galerii Sfera.',
    full_description: 'Bolek i Lolek to postacie stworzone przez Studio Filmów Rysunkowych w Bielsku-Białej w 1963 r. Pomnik przy Galerii Sfera przedstawia obu bohaterów wskazujących na globus — symbol ich podróży.',
    latitude: 49.826290,
    longitude: 19.048180,
    address: 'ul. Mostowa, przy Galerii Sfera, 43-300 Bielsko-Biała',
    category_id: 'cat-culture',
    organization_id: null,
    cover_image: null,
    gallery: [],
    hint: 'Pomnik stoi przy głównym wejściu od strony ul. Mostowej.',
    task_content: 'Podejdź do pomnika. Na co wskazują Bolek i Lolek?',
    unlockable_content: null,
    verification_type: 'answer',
    verification_data: {
      question: 'Na co wskazują Bolek i Lolek?',
      answer: 'globus',
      accepted_answers: ['globus', 'na globus'],
    } as any,
    gps_radius: 60,
    is_active: true,
    is_promoted: false,
    event_start: null,
    event_end: null,
    accessibility: 'chodnik przed Galerią Sfera',
    created_at: now,
    updated_at: now,
  },
  {
    // Etap 4 — Teatr Polski
    id: 'place-teatr',
    name: 'Teatr Polski w Bielsku-Białej',
    slug: 'teatr-polski-bielsko',
    type: 'city',
    short_description: 'Zabytkowy teatr dramatyczny — najstarszy teatr zawodowy na polskim Śląsku.',
    description: 'Teatr Polski działa nieprzerwanie od 1890 r. Budynek przy ul. 1 Maja to jeden z najpiękniejszych przykładów architektury neoklasycznej w mieście.',
    full_description: 'Teatr Polski w Bielsku-Białej to najstarszy zawodowy teatr na polskim Śląsku, założony w 1890 r. Fasada budynku utrzymana jest w stylu neoklasycznym z charakterystycznymi kolumnami przy głównym wejściu.',
    latitude: 49.819975,
    longitude: 19.047137,
    address: 'ul. 1 Maja 1, 43-300 Bielsko-Biała',
    category_id: 'cat-culture',
    organization_id: null,
    cover_image: null,
    gallery: [],
    hint: 'Stań przed głównym wejściem i policz elementy fasady.',
    task_content: 'Stań przed głównym wejściem. Ile kolumn widzisz?',
    unlockable_content: null,
    verification_type: 'answer',
    verification_data: {
      question: 'Ile kolumn widzisz przy głównym wejściu?',
      answer: '4',
      accepted_answers: ['4', 'cztery'],
    } as any,
    gps_radius: 60,
    is_active: true,
    is_promoted: false,
    event_start: null,
    event_end: null,
    accessibility: 'chodnik przy ul. 1 Maja',
    created_at: now,
    updated_at: now,
  },
  {
    // Etap 5 — Pomnik Reksia
    id: 'place-reksio',
    name: 'Pomnik Reksia',
    slug: 'pomnik-reksia',
    type: 'city',
    short_description: 'Kultowy piesek z bielskiego studia animacji — ostatni etap spaceru.',
    description: 'Reksio to kolejna bajkowa postać Studia Filmów Rysunkowych w Bielsku-Białej. Pomnik przy moście nad Białą zamyka bajkowy szlak spaceru.',
    full_description: 'Reksio — kultowy piesek z serialu animowanego produkowanego przez bielskie Studio Filmów Rysunkowych od 1967 r. — doczekał się własnego pomnika przy moście nad rzeką Białą. To ostatni etap spaceru przez centrum. Gratulacje!',
    latitude: 49.823194,
    longitude: 19.048306,
    address: 'ul. 11 Listopada, przy moście nad Białą, 43-300 Bielsko-Biała',
    category_id: 'cat-culture',
    organization_id: null,
    cover_image: null,
    gallery: [],
    hint: 'Szukaj przy moście nad rzeką Białą, przy ul. 11 Listopada.',
    task_content: 'Znajdź pomnik Reksia i zalicz go przez GPS.',
    unlockable_content: 'Brawo! Ukończyłeś spacer przez centrum Bielska-Białej. Bielsko-Biała to miasto dwóch bajkowych studiów — Studio Filmów Rysunkowych przez dekady tworzyło tu Bolka i Lolka, Reksia i wiele innych postaci. Odwiedź muzeum i poznaj kulisy tych produkcji!',
    verification_type: 'gps',
    verification_data: { radius: 60 },
    gps_radius: 60,
    is_active: true,
    is_promoted: false,
    event_start: null,
    event_end: null,
    accessibility: 'chodnik przy moście',
    created_at: now,
    updated_at: now,
  },
]

export const DEMO_QUESTS: Quest[] = [
  {
    id: 'quest-ngo',
    title: 'Odkryj NGO w Bielsku-Białej',
    slug: 'odkryj-ngo-w-bielsku-bialej',
    description: 'Krótki quest prowadzący przez punkty społeczne i pokazujący, czym zajmują się lokalne organizacje.',
    theme: 'społeczne bielsko',
    cover_image: null,
    difficulty: 'easy',
    estimated_time: 60,
    completion_conditions: { min_steps: 2 },
    reward_description: 'Po ukończeniu dostajesz odznakę Odkrywca NGO.',
    badge_id: 'badge-ngo',
    is_active: true,
    is_featured: true,
    category_id: 'cat-quest',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'quest-city',
    title: 'Spacer przez centrum',
    slug: 'spacer-przez-centrum',
    description: 'Poznaj centrum Bielska-Białej z nowej perspektywy. Od rynku i zamku po bajkowe pomniki i Teatr Polski — ten spacer łączy historię miasta z jego popkulturowym charakterem.',
    theme: 'miasto',
    cover_image: null,
    difficulty: 'easy',
    estimated_time: 45,
    completion_conditions: { min_steps: 5 },
    reward_description: 'Za ukończenie dostajesz odznakę Odkrywca Bielska.',
    badge_id: 'badge-odkrywca',
    is_active: true,
    is_featured: true,
    category_id: 'cat-quest',
    created_at: now,
    updated_at: now,
  },
]

export const DEMO_QUEST_STEPS: QuestStep[] = [
  // ─── Quest: Odkryj NGO ──────────────────────────────────────────────────────
  {
    id: 'step-ngo-1',
    quest_id: 'quest-ngo',
    place_id: 'place-zf',
    step_number: 1,
    title: 'Poznaj pierwszą organizację',
    description: 'Zalicz punkt Zakątek Fantastyki.',
    hint: null,
    task_content: null,
    is_optional: false,
    created_at: now,
  },
  {
    id: 'step-ngo-2',
    quest_id: 'quest-ngo',
    place_id: 'place-wsparcie',
    step_number: 2,
    title: 'Odkryj punkt wsparcia',
    description: 'Sprawdź miejsce, które pomaga mieszkańcom.',
    hint: null,
    task_content: null,
    is_optional: false,
    created_at: now,
  },

  // ─── Quest: Spacer przez centrum ────────────────────────────────────────────
  {
    id: 'step-city-1',
    quest_id: 'quest-city',
    place_id: 'place-rynek',
    step_number: 1,
    title: 'Rynek',
    description: 'Zacznij od serca starego miasta. Znajdź fontannę Neptuna.',
    hint: 'Fontanna stoi pośrodku płyty rynku.',
    task_content: 'Znajdź fontannę Neptuna. Co trzyma Neptun w dłoni?',
    is_optional: false,
    created_at: now,
  },
  {
    id: 'step-city-2',
    quest_id: 'quest-city',
    place_id: 'place-zamek',
    step_number: 2,
    title: 'Zamek Sułkowskich',
    description: 'Przejdź na wzgórze zamkowe i sprawdź jego historię.',
    hint: 'Tablica informacyjna przy wejściu do zamku.',
    task_content: 'Spójrz na informacje o zamku. Z którego wieku pochodzi zamek?',
    is_optional: false,
    created_at: now,
  },
  {
    id: 'step-city-3',
    quest_id: 'quest-city',
    place_id: 'place-bolek',
    step_number: 3,
    title: 'Bolek i Lolek',
    description: 'Odwiedź pomnik kultowych postaci bielskiego studia animacji.',
    hint: 'Pomnik stoi przy Galerii Sfera, od strony ul. Mostowej.',
    task_content: 'Podejdź do pomnika. Na co wskazują Bolek i Lolek?',
    is_optional: false,
    created_at: now,
  },
  {
    id: 'step-city-4',
    quest_id: 'quest-city',
    place_id: 'place-teatr',
    step_number: 4,
    title: 'Teatr Polski',
    description: 'Stań przed najstarszym zawodowym teatrem na polskim Śląsku.',
    hint: 'Wejście od ul. 1 Maja — patrz na fasadę.',
    task_content: 'Stań przed głównym wejściem. Ile kolumn widzisz?',
    is_optional: false,
    created_at: now,
  },
  {
    id: 'step-city-5',
    quest_id: 'quest-city',
    place_id: 'place-reksio',
    step_number: 5,
    title: 'Reksio',
    description: 'Zakończ spacer przy pomniku kultowego pieska bielskiej animacji.',
    hint: 'Pomnik przy moście nad Białą, ul. 11 Listopada.',
    task_content: 'Znajdź pomnik Reksia i zalicz go przez GPS.',
    is_optional: false,
    created_at: now,
  },
]

export const DEMO_QR_CODES: QRCode[] = [
  { id: 'qr-zamek', code: 'BIELSKO-ZAMEK', place_id: 'place-zamek', is_active: true, is_single_use: false, scan_count: 0, created_at: now },
]

export const DEMO_USER_PROFILES: UserProfile[] = [
  {
    id: 'user-demo',
    username: 'demo',
    display_name: 'Demo Odkrywca',
    avatar_url: null,
    bio: 'Konto demonstracyjne do testów aplikacji.',
    explorer_level: 1,
    total_points: 0,
    home_city: 'Bielsko-Biała',
    is_admin: false as any,
    created_at: now,
    updated_at: now,
  } as UserProfile,
  {
    id: 'user-admin',
    username: 'admin',
    display_name: 'Admin Demo',
    avatar_url: null,
    bio: 'Administrator demonstracyjny.',
    explorer_level: 3,
    total_points: 120,
    home_city: 'Bielsko-Biała',
    is_admin: true as any,
    created_at: now,
    updated_at: now,
  } as UserProfile,
]

export const DEMO_AUTH_USERS = [
  { id: 'user-demo', email: 'demo@miejski.pl', password: 'demo123', is_admin: false },
  { id: 'user-admin', email: 'admin@miejski.pl', password: 'admin123', is_admin: true },
]

export const DEMO_CHECKINS: Checkin[] = []
export const DEMO_USER_PROGRESS: UserProgress[] = []
export const DEMO_USER_BADGES: UserBadge[] = []
